[phases.setup]
nixPkgs = ['nodejs-20_x', 'npm']

[phases.install]
cmds = ['npm ci --production=false']

[phases.build]
cmds = ['npm run build']

[phases.start]
cmd = 'npm start'

[variables]
NODE_VERSION = '20.19.0'
NPM_VERSION = '10.2.4'
NODE_ENV = 'production'